cc_library(
    name = "container",
    hdrs = ["F14Set.h"],
    deps = ["//folly:cportability", "//folly:portability", ":View"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "View",
    hdrs = ["View.h"],
    deps = ["//folly/functional:invoke"],
)
