cc_library(
    name = "container",
    hdrs = ["F14Set.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":View",
        "//folly:cportability",
        "//folly:portability",
    ],
)

cc_library(
    name = "View",
    hdrs = ["View.h"],
    deps = ["//folly/functional:invoke"],
)
