cc_library(
    name = "invoke",
    hdrs = ["Invoke.h"],
    deps = ["//folly:cppattributes", "//folly:portability", "//folly:preprocessor", "//folly:traits",  "//folly:utility", "//folly/lang:customizationpoint"],
    visibility = ["//visibility:public"],
)
