cc_library(
    name = "invoke",
    hdrs = ["Invoke.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//folly:cppattributes",
        "//folly:portability",
        "//folly:preprocessor",
        "//folly:traits",
        "//folly:utility",
        "//folly/lang:customizationpoint",
    ],
)
