cc_library(
    name = "ApplyTuple",
    hdrs = ["ApplyTuple.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//folly:Traits",
        "//folly:Utility",
        "//folly/functional:Invoke",
    ],
)

cc_library(
    name = "Invoke",
    hdrs = ["Invoke.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//folly:CppAttributes",
        "//folly:Portability",
        "//folly:Preprocessor",
        "//folly:Traits",
        "//folly:Utility",
        "//folly/lang:CustomizationPoint",
    ],
)
